export enum EstadoDocumento {
  INGRESADO = 'INGRESADO',
  PENDIENTE = 'PENDIENTE',
  ATENDIDO = 'ATENDIDO',
  DERIVADO = 'DERIVADO',
  ELIMINADO = 'ELIMINADO',
  OBSERVADO = 'OBSERVADO',
  OTROS = 'OTROS'
}
